### ISSUE TITLE
Unknown authentication strategy "slack"

### ISSUE THREAD

**Issue by ktkaushik** [nmaves/passport-slack-oauth2#4]
I installed and loaded it like so - 

```javascript
const SlackStrategy     = require('passport-slack-oauth2').Strategy
```

```javascript
passport.use(new SlackStrategy({
        clientID    : secret.slack.id,
        clientSecret: secret.slack.secret,
        skipUserProfile: false,
        callbackURL: 'https://123456789.ngrok.io/sessions/slack/callback',
        scope: ['channels:read', 'chat:write:bot']
 
    }, (accessToken, scopes, profile, done) => {
        // optionally persist profile data
        done(null, profile)
    }
));
```

On my routes, i am using the middleware to authorize slack but i keep getting error  as unknown authentication strategy slack

```javascript
// path to start the OAuth flow
router.get('/sessions/slack', passport.authorize('slack'));

// OAuth callback url
router.get('/sessions/slack/callback', 
	passport.authorize('slack', { failureRedirect: '/login' }),
	(req, res) => res.redirect('/')
)
```

**Comment by ktkaushik** [comment]
Error log is - 

```javascript
Unknown authentication strategy "slack"
Error: Unknown authentication strategy "slack"
    at attempt (/Users/Kaushik/dev/testproject.sh/testproject/node_modules/passport/lib/middleware/authenticate.js:186:37)
    at authenticate (/Users/Kaushik/dev/testproject.sh/testproject/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at Layer.handle [as handle_request] (/Users/Kaushik/dev/testproject.sh/testproject/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/Kaushik/dev/testproject.sh/testproject/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/Kaushik/dev/testproject.sh/testproject/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/Kaushik/dev/testproject.sh/testproject/node_modules/express/lib/router/layer.js:95:5)
    at /Users/Kaushik/dev/testproject.sh/testproject/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/Kaushik/dev/testproject.sh/testproject/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/Kaushik/dev/testproject.sh/testproject/node_modules/express/lib/router/index.js:275:10)

```

**Comment by ktkaushik** [comment]
@nmaves any idea why this might be happening?

**Comment by nmaves** [comment]
To be fair I have not looked at nor touched this code in over two years. It might be a case sensitivity issue.  Can you try `passport.authorize('Slack')` with a capital S

**Comment by ktkaushik** [comment]
I tried but it didn't work. On the other hand, i made `passport-slack` work by removing scopes in the strategy and adding a **Add to Slack** button. So, i am going with that.

**Comment by AnthonyMouallem** [comment]
any updates?

**Comment by scipe** [comment]
Guys you need:
1. ```
const SlackStrategy = require('passport-slack-oauth2').Strategy```
2. ```passport.authenticate('Slack')```

**Comment by nmaves** [comment]
Closing this as there appears to be a solution/workaround.
